name: Deploy Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init

